### PR TITLE
Introduce CategoryCarouselVC

### PR DESCRIPTION
**Pull request by Clstroud**
Depends on #288 

# Description of Work

* Reintroduces portions of the root UI 
* Fixes issues stemming from previous GazeableButton sizing and styling implementation
* Root category carousel automatically selects visible category when in compact width
 
## Notes to Test
* Layout changes are still needed; I'm just trying to get the core features back in at the moment
---
category_scroll

### CODE REVIEW

**Comment by stechkev** [comment]
auto selection of visible carousel category is currently not working.

**Comment by stechkev** [comment]
carousel automatically selects visible category when in compact width -> currently not working

**Review by stevefosterwta — APPROVED** [review]
🪐 👍

**Comment by stechkev** [comment]
test approved

**Pull request merged**
