### PR TITLE
New Crowdin updates

### PR DESCRIPTION
**Pull request by Clstroud**

### CODE REVIEW

**Comment by rowildcard** [comment]
@Clstroud , @SashankPatel 
I don't know what to test in this PR. It looks like the English note in each localization was changed but it doesn't appear the corresponding translation changed. 
Is there a 1-to-1 correlation? 
Does someone else take on the task of translating each language? 
Is this just a backend change?

**Comment by SashankPatel** [comment]
@rowildcard: These PRs are auto generated based on our updates in develop.  Theres really no testing required, its just crowdin syncing up the language updates.  Yes someone else and or auto translation service takes care of translating the strings.  i.e. if we remove/update strings, crowdin will update the language files and accordingly to remove the translation.

Also Chris' name is on it because it's his git account that linked/integrated with Crowdin.

**Comment by rowildcard** [comment]
> 
@SashankPatel 
What's the next step, then? 
Will Chris just merge whenever the checks pass?

**Comment by SashankPatel** [comment]
@rowildcard : Yup, with these PRs its typically an approve and merge - The PR title and Branch name will always be the same so we know that its a Crowdin auto generated PR.  Chris and I have been trying to figure out the CI failure and experimenting solutions.

**Comment by SashankPatel** [comment]
Closing this and will delete the branch so a new one can be created.

**Pull request closed without merging**
